;  IDL script to read out from rhs (obtained with idgn77 > 0)

;  Version for case with diffusion, and with storage of zz
;  =======================================================

!p.charsize=1.3
!x.range=[400,460]

; IDL Version 5.2 (IRIX mipseb)
; Journal File for jcd@bigcat
; Working directory: /scratch/tac/usr/jcd/emdl94/dimauro
; Date: Tue Dec 21 09:43:19 1999
device,retain=2
 
nrdmax=50
nn=0l
nvar=0l
dt=0.d0
openr,1,'ttt.rhs',/f77
readu,1,nn,nvar,dt
print,nn,nvar,dt
;         601           9
iter=0l
ialamw=0l
iyfdst=0l
nrd=-1
while not eof(1) and nrd lt nrdmax do begin $
  readu,1,iter, ialamw, iyfdst &$
  if nrd eq -1 then begin $
    xyfr=dblarr(iyfdst,nn) &$
    xyf=dblarr(iyfdst,nn,nrdmax) &$
  endif &$
  print,iter, ialamw, iyfdst &$
  nrd=nrd+1 &$
  readu,1,xyfr &$
  xyf(*,*,nrd)=xyfr  &$
endwhile

xyf=xyf(*,*,0:nrd)

close,1
read_nemdls,1,nn,ndata,datmod,idatmd,bc,x,y, $
  file='ttt.emdl'
close,1

xf=reform(xyf(0,*,*))

yf=reform(xyf(1:nvar,*,*),nvar,nn,nrd+1)

zz=reform(xyf(nvar+1:2*nvar,*,*),nvar,nn,nrd+1)

ff=reform(xyf(2*nvar+1:3*nvar,*,*),nvar,nn,nrd+1)

fd=reform(xyf(1+3*nvar:nvar*nvar+3*nvar,*,*),nvar,nvar,nn,nrd+1)

print,'End setting xf, yf, zz, ff, fd'

ialam=0
iyfdst_al = 1+nvar*(3+ialamw+(1+ialamw)*nvar)
if iyfdst ge iyfdst_al then begin $
  print,'Including alam' &$
  alam=reform(xyf(1+nvar*(3+nvar):nvar*(3+ialamw+nvar),*,*),ialamw,nvar,nn,nrd+1) &$
  alamd=reform(xyf(1+nvar*(3+ialamw+nvar):nvar*(3+ialamw+(1+ialamw)*nvar),*,*), $
                 ialamw,nvar,nvar,nn,nrd+1) &$
  ialam=1 &$
endif

idiffus=0
if iyfdst gt iyfdst_al then begin $
  idiffus = 1 &$
  print,'Including diffusion quantities' &$
  diffus=reform(xyf(iyfdst_al:iyfdst-1,*,*)) &$
  ddr=reform(diffus(4,*,*)-diffus(3,*,*)) &$
endif

dyf=yf
for i=0,nrd do begin $
  for j=0,nvar-1 do dyf(j,0:nn-2,i)=(yf(j,1:nn-1,i)-yf(j,0:nn-2,i))/ $
			  (xf(1:nn-1,i)-xf(0:nn-2,i)) &$
endfor

print,'End setting dyf'

dzz=zz
for i=0,nrd do begin $
  for j=0,nvar-1 do dzz(j,0:nn-2,i)=(zz(j,1:nn-1,i)-zz(j,0:nn-2,i))/ $
			  (xf(1:nn-1,i)-xf(0:nn-2,i)) &$
endfor

print,'End setting dzz'

ffm=ff
for i=0,nrd do begin $
  for j=0,4 do ffm(j,0:nn-2,i)=0.5*(ff(j,1:nn-1,i)+ff(j,0:nn-2,i)) &$
endfor

print,'End setting ffm'

;dxyf=reform(yf(4,*,*)+yf(6,*,*)-0.98d0)

ntst=n_elements(yf(0,0,*))-1

dff=0*ff 
dfft=0*fd 
for ktst=1,ntst do begin $
  for i=0,nvar-1 do begin $
    for j=0,nvar-1 do begin &$
      dfft(i,j,*,ktst)=fd(i,j,*,ktst)*(yf(j,*,ktst)-yf(j,*,ktst-1)) &$
      dff(i,*,ktst)=dff(i,*,ktst)+dfft(i,j,*,ktst) &$
    endfor &$
  endfor &$
endfor


if ialam then begin $
  dalam=0*alam &$
  dalamt=0*alamd &$
  for ktst=1,ntst do begin $
    for ia=0,ialamw-1 do begin &$
      for i=0,nvar-1 do begin &$
        for j=0,nvar-1 do begin &$
          dalamt(ia,i,j,*,ktst)= $
	    alamd(ia,i,j,*,ktst)*(yf(j,*,ktst)-yf(j,*,ktst-1)) &$
          dalam(ia,i,*,ktst)=dalam(ia,i,*,ktst)+dalamt(ia,i,j,*,ktst) &$
        endfor &$
      endfor &$
    endfor &$
  endfor &$
endif

ffg=0.*reform(ff(4,*,*))
ffmt=ffg
if ialam then begin &$
  for k=0,nrd do begin &$
    for i=0,5 do ffg(*,k)=ffg(*,k)+alam(0,i,*,k)*(yf(i,*,k)-yf(i,*,0))/dt &$
    ffmt(0:nn-2,k)=ffm(4,0:nn-2,k)+0.5d0*(ffg(0:nn-2,k)+ffg(1:nn-1,k)) &$
  endfor &$
endif
 
a4=datmod(22,0)/1.d33

eps=reform(ff(4,*,*)/(a4*10.d0^(xf-yf(4,*,*))))

epsg=reform(ffg(*,*)/(a4*10.d0^(xf-yf(4,*,*))))
alshft=7.45446d-3

epsav=reform((10.d0^yf(4,*,*)-alshft)/(a4*10.d0^xf))

xf=xf(*,0)
q=10.d0^xf

dlxdpl=reform(yf(3,*,*))
for i=0,nrd do dlxdpl(*,i)=reform(deriv(zz(1,*,i),alog10(yf(3,*,i))))
rhxp=reform(-5*yf(3,*,*)/(3+5*yf(3,*,*)-yf(4,*,*)))
dtxh=dlxdpl*rhxp

gradt=reform(ff(2,*,*)/ff(1,*,*))

for i=0,ntst do begin $
  print,i & plot,yf(4,*,i),xr=[400,500],psym=-1 & swait,-1 & endfor
